In [1]:
import numpy as np

In [3]:
A = np.array([[4,-5],[-2,3]])
print(A)

[[ 4 -5]
 [-2  3]]


In [4]:
b = np.array([[-13],[9]])
print(b)

[[-13]
 [  9]]


In [44]:
np.linalg.inv(A).dot(b)

matrix([[3.],
        [5.]])

In [38]:
A = np.asmatrix(A)
b = np.asmatrix(b)

In [39]:
A.I*b

matrix([[3.],
        [5.]])

In [6]:
import numpy as np
p = np.matrix([[0,0],
             [0, 1]])
x = np.matrix([[1],
              [1]])
y= p*x
print(y)

[[0]
 [1]]


In [42]:
x = np.asmatrix(x)
y = np.asmatrix(y)

x.T*y

matrix([[5]])

In [43]:
z= x.T*y
print(z)

[[5]]


In [45]:
x = np.array([[4],
              [3]])
print(x)

[[4]
 [3]]


In [46]:
np.linalg.norm(x)

5.0

In [47]:
np.linalg.norm(x,2)

5.0

In [48]:
np.linalg.norm(x,1)

7.0

In [53]:
x = np.asmatrix([[1],
                 [2]])
y = np.asmatrix([[2],
                [-1]])
x.T*y

matrix([[0]])

In [9]:
import numpy as np
A = np.array([[1,2,1],
             [0,3,5],
             [3,7,5]])
D,V=np.linalg.eig(A)
print(V)

[[-0.20171182 -0.74126885  0.33565412]
 [-0.54605595  0.57201394 -0.70887172]
 [-0.81310223 -0.35117025  0.62035248]]
