In [2]:
import numpy as np

theta = 90/180*np.pi
R = np.matrix([[np.cos(theta), -np.sin(theta)],
               [np.sin(theta), np.cos(theta)]])
x = np.matrix([[1],[0]])

y = R*x
print(y)

[[6.123234e-17]
 [1.000000e+00]]


In [3]:
import numpy as np

P = np.matrix([[1, 0],
               [0, 0]])
x = np.matrix([[1],
               [1]])

y = P*x
print(y)

[[1]
 [0]]


In [5]:
import numpy as np

A = np.array([[1, 0],
              [0, 0]])
D, V = np.linalg.eig(A)
print(D)
print(V)

[1. 0.]
[[1. 0.]
 [0. 1.]]


In [12]:
import numpy as  np

X = np.matrix([[3],
               [7]])
Y = np.matrix([[0],
               [8]])

omega = (X.T*Y)/(Y.T*Y)
omega = float(omega)
print(float(omega))
W = omega*Y
print(W)

0.875
[[0.]
 [7.]]


In [2]:
print(Y.T*Y)

[[26]]


In [3]:
omega = (X.T*Y)/(Y.T*Y)
omega = float(omega)
print(float(omega))

0.7307692307692307


In [4]:
W = omega*Y
print(W)

[[3.65384615]
 [0.73076923]]


In [14]:
import numpy as  np

A = np.matrix([[1,0],
               [0,1],
               [0,0]])
B = np.matrix([[5],
               [3],
               [9]])

X = (A.T*A).I*A.T*B
print(X)

Bstar = A*X
print(Bstar)

[[5.]
 [3.]]
[[5.]
 [3.]
 [0.]]


In [10]:
import numpy as np
A = np.array([[5],
             [4]])
A = np.asmatrix(A)
q1 = np.linalg.norm(A,1)
q2 = np.linalg.norm(A,2)
print(q1)
print(q2)

9.0
6.4031242374328485


In [11]:
A = np.array([[1],
             [2]])
A = np.asmatrix(A)
print(A)

[[1]
 [2]]


In [11]:
import numpy as np
a = np.array([[1,4,2]])
b = np.array([[1,0,1]])
z= a.T*b.T
theta = z *np.pi
R = np.cos(theta)
print(2*R)


[[-2.]
 [ 2.]
 [ 2.]]


In [3]:
theta = z *np.pi
print(theta)

[[3.14159265]
 [0.        ]
 [6.28318531]]
